sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sanjeevdotextrabox/docker_cloud -f Dockerfile.dev .

script:
  - docker run -e CI=true sanjeevdotextrabox/docker_cloud  npm run test
